### PR TITLE
Select dropdowns now select media properly in, Inter font is loaded

### PR DESCRIPTION
**Pull request by ronak0624**
Here is the fix for the select audio video bug. The absolute positioned menu list was not considered a child of the outside click detector.

### CODE REVIEW

**Comment by eshajoshi** [comment]
Hey @ronak0624 nice job! Couple things --

1. The Camera Dropdown is detecting the alternate video source but I am not able to change sources to the FaceTime HD camera. (see screenshot #1)
2. Also the font of the camera and microphone options aren't in line with what's on the designs (what we've been using - Inter). Do you mind please investigating that?
3. I'm not able to scroll down on the Audio microphone list. Could you please check out? (See screenshot 2)

image

image

**Comment by dhlanm** [comment]
Looks good! One small thing--the text color is inheriting from the browser settings. So, since I have dark mode on github, the text from the dropdown ends up being white-on-white for github. Should be fixed by explicitly styling the text.

**Comment by ronak0624** [comment]
> The Camera Dropdown is detecting the alternate video source but I am not able to change sources to the FaceTime HD camera. (see screenshot 1)

Are you completely blocked from switching sources? Or does it only work sometimes? I am still able to switch between two cameras when building from this branch. I can link a demo video if needed. 

> Looks good! One small thing--the text color is inheriting from the browser settings. So, since I have dark mode on github, the text from the dropdown ends up being white-on-white for github. Should be fixed by explicitly styling the text.

Thank you for spotting this! I was under the assumption that this was only being used in Google Slides until more functionality is added, so I wasn't testing for that, a fix is up now. 

For the font itself, there is a fix included to just get rid of the default serif font to start. In order to package the 'Inter' font directly with the extension, it has to be converted, then setup in Webpack, then set up in the Manifest, then loaded in via content script in order to use it with the React components. Right now, none of the documented methods of doing these steps are working as intended, so I will need a bit more time to get that packaged font in.

**Comment by dhlanm** [comment]
Looks good to me. @eshajoshi could you take a look and see if you're able to switch webcams since you were having an issue with it before? otherwise good to merge in I think

**Pull request merged**
